### ISSUE TITLE
Crash during argument parsing

### ISSUE THREAD

**Issue by R1kM** [AeneasVerif/charon#403]
Running Charon on crate `lazy-static.rs` leads to a panic with error message 
```
thread 'main' panicked at src/bin/charon-driver/driver.rs:170:5:
assertion failed: indices.len() <= 1
```

One hypothesis raised by @Nadrieril is that this is due to the crate name ending in `.rs`, that should be better handled during argument parsing.

**Comment by zjp-CN** [comment]
Reproduce this issue with:

1. a.rs
2. `charon --print-llbc --no-cargo --rustc-arg=a.rs --rustc-arg=--crate-name=a.rs`

```rust
// a.rs
fn main() {}
```

```bash
$ charon --print-llbc --no-cargo --rustc-arg=a.rs --rustc-arg=--crate-name=a.rs
thread 'main' panicked at src/bin/charon-driver/driver.rs:225:5:
assertion failed: indices.len() <= 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Problematic code: https://github.com/AeneasVerif/charon/blob/fc7599d31f4e105c674be785bad636d9d25c02f0/charon/src/bin/charon-driver/driver.rs#L223
